spring:
  application:
    name: dubbo-consumer
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.freedom.mytest.consumer.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: N/A

server:
  port: 8080
